### ISSUE TITLE
django modeling

### ISSUE THREAD

**Issue by bbelderbos** [abaddonpuff/commandCenter#1]
Please define the models / tables you want to use and how they relate

**Comment by bbelderbos** [comment]
+ project setup -> first PR?

**Comment by abaddonpuff** [comment]
I have no Idea why the PR did not showup. I did check before leaving yesterday. Will submit again

**Comment by bbelderbos** [comment]
Hm weird, so no way to reproduce this to know what happened? Anyways, I have it now ...
