### ISSUE TITLE
Twitter (X) API

### ISSUE THREAD

**Issue by bbelderbos** [abaddonpuff/commandCenter#2]
Retrieve tweet data from the API

**Comment by bbelderbos** [comment]
@abaddonpuff I still have an app with key/secret, but I was wondering if we even need this for public data?

What library will you use? I think Tweepy does the job pretty well!

https://docs.tweepy.org/en/latest/getting_started.html

**Comment by abaddonpuff** [comment]
Oh! But Tweepy will be deprecated T_T they are moving now to X_API 
https://developer.twitter.com/en/docs/twitter-api/getting-started/make-your-first-request

There are some libraries like
https://github.com/xdevplatform/search-tweets-python/blob/master/searchtweets/result_stream.py

I wouldn't like to rely too much on external libraries as I feel I will not learn much though, what do you think.

**Comment by bbelderbos** [comment]
Oh sorry, should have checked. And that is a good point. So requests should be more bare bones and hopefully works with the new X API ...

**Comment by bbelderbos** [comment]
@abaddonpuff what does only post mean? Can we even retrieve stuff on the free version?

<img width="950" alt="image" src="https://github.com/abaddonpuff/commandCenter/assets/387927/055c89a8-bea5-4968-8b1e-e62b59dede3c">

**Comment by bbelderbos** [comment]
Maybe good to check this first and if not free, we work on a different provider first?

**Comment by abaddonpuff** [comment]
I made it work. But it does need the paid version to be able to query other people T____T.
<img width="549" alt="image" src="https://github.com/abaddonpuff/commandCenter/assets/25719314/fd579b82-7a2f-45d1-9d6e-bfb259e3d4ae">

**Comment by bbelderbos** [comment]
Awesome, great job. Can you PR the fix? Still surprised this is not free :( - what is the pricing like?

**Comment by abaddonpuff** [comment]
I PR the fix, its 100$ a month :P

**Comment by bbelderbos** [comment]
Man that is expensive, is that enterprise only then?

**Comment by bbelderbos** [comment]
Is that unique tweets btw? Wonder if you want to cache them in the DB because you only get a limited amount:

<img width="1079" alt="image" src="https://github.com/abaddonpuff/commandCenter/assets/387927/ccefa0c8-9984-4098-a139-d41aa215fdfe">

**Comment by abaddonpuff** [comment]
I managed to get a discounted Basic version. Will begin working tomorrow morning on the project. :D Wish you a happy conference.
