### ISSUE TITLE
Issues using HTMX

### ISSUE THREAD

**Issue by abaddonpuff** [abaddonpuff/commandCenter#33]
I think I have the correct idea but, currently cannot successfully execute. 

The idea I'm trying to do is to submit a django form that gets rendered into the same website. for which I have this piece of code.

`<form method="post" action="{% url 'show_all_artists' %}" hx-post="{% url 'show_all_artists' %}" hx-target="#artistChoicesContainer">
        <br>
        {% csrf_token %}
        {{ spotify_search_form.as_p }}
    </form>
        <button type="submit">Search Artist</button>

    <div id="artistChoicesContainer">
        
    </div>`

Then the results will be downloaded into the div using HTMX.

But everytime I reload, The text box does not render. I see that the program is going through the right flow when I debug. but this portion of the form does not render

`class SpotifySearchForm(forms.Form):
    artist = forms.CharField(label='Search for an artist', max_length=100)`

I tried submiting through different URL calls and to extend the usage of the call without much success. Super stuck right now.

**Comment by abaddonpuff** [comment]
I think I unblocked myself... as I typed the previous issue

**Comment by abaddonpuff** [comment]
I See the response in the view. But cannot find a way to extract or debug the values I need.

**Comment by bbelderbos** [comment]
> I think I unblocked myself... as I typed the previous issue

Rubber duck debugging 😍 📈

**Comment by bbelderbos** [comment]
OK good work, I will comment in the PR...
