### ISSUE TITLE
Create Slackbot to notify for new item

### ISSUE THREAD

**Issue by abaddonpuff** [abaddonpuff/commandCenter#40]
Create a Slackbot to automate notifying for new posts

**Comment by bbelderbos** [comment]
Oh this is cool!

Did a starter video on our youtube:

How to build a simple Slack bot using the Bolt framework for Python
https://www.youtube.com/watch?v=oDoFvpDftBA

**Comment by bbelderbos** [comment]
btw if you want to search our content from the cli, try this:

1. install rust
2. cargo install pybites-search

```
$ psearch --help
A command-line search tool for Pybites content

Usage: psearch [OPTIONS] [SEARCH_TERMS]...

Arguments:
  [SEARCH_TERMS]...

Options:
  -c, --content-type <CONTENT_TYPE>
  -t, --title-only
  -h, --help                         Print help
  -V, --version                      Print version
```

**Comment by bbelderbos** [comment]
@abaddonpuff can you spec this issue out a bit more please?

**Comment by abaddonpuff** [comment]
Got this working! 

<img width="395" alt="image" src="https://github.com/abaddonpuff/commandCenter/assets/25719314/0ec4f912-158c-4fc1-be76-398360d1dbdf">

**Comment by abaddonpuff** [comment]
I need to invite you to my test workspace :) so you can see too

**Comment by bbelderbos** [comment]
Nice please do so, you can use my pybites email, it doesn't matter which email right?

**Comment by bbelderbos** [comment]
I am in! Super cool this feature, well done!
