### ISSUE TITLE
Help on grabbing the artist_id directly from dropdown

### ISSUE THREAD

**Issue by abaddonpuff** [abaddonpuff/commandCenter#42]
I've been trying to work on showing the dropdown meny with artist name and popularity to avoid grabbing the wrong artist

One thing I do not understand is how is it taking the value from the dropdown. I was trying to pass  artist_id in the options but showing only the artist and popularity but it is still taking the Artist name from it on views.get_artists():

`options = ''.join(
        "<option value='{artist_id}'>{val}, Popularity: {pop}, artist_id: {artist_id}, </option>".format(val=row[0], pop=row[2], artist_id=row[3]) for row in response
    )`

**Comment by bbelderbos** [comment]
Not sure I understand, let's look at this in our meeting today ...

**Comment by bbelderbos** [comment]
You had it right, the arist id was in option's value so was part of the request.POST, the bigger issue is `get_spotify_artist_by_id` returning text, needs to be json (`response.json()`)

Debugging output from call:

```
(Pdb) artist
'shakira'
(Pdb) artist_metadata["images"]
[{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5ebaee73c0f0458b95091845ee1', 'width': 640}, {'height': 320, 'url': 'https://i.scdn.co/image/ab67616100005174aee73c0f0458b95091845ee1', 'width': 320}, {'height': 160, 'url': 'https://i.scdn.co/image/ab6761610000f178aee73c0f0458b95091845ee1', 'width': 160}]
(Pdb) artist_metadata["images"][0]
{'height': 640, 'url': 'https://i.scdn.co/image/ab6761610000e5ebaee73c0f0458b95091845ee1', 'width': 640}
(Pdb) artist_metadata["images"][0]["url"]
'https://i.scdn.co/image/ab6761610000e5ebaee73c0f0458b95091845ee1'
(Pdb) artist_metadata["popularity"]
85
```
