### ISSUE TITLE
Reset DB or remove test fields

### ISSUE THREAD

**Issue by abaddonpuff** [abaddonpuff/commandCenter#44]
While testing I introduced things I don't want into the databases. What would be the smoothest way to delete them. Through admin?

**Comment by bbelderbos** [comment]
Yes admin is easier, or connect to the db and do it through the db gui or raw sql. Let's see on our call why this happened and how to prevent it, maybe need some more encapsulation / dependency injection in your tests ...

**Comment by bbelderbos** [comment]
Btw tests should use an independent in-memory db, should not mess with your developer db.

**Comment by abaddonpuff** [comment]
This should be good to close
