### ISSUE TITLE
Issue when migrating blocking me :( 

### ISSUE THREAD

**Issue by abaddonpuff** [abaddonpuff/commandCenter#46]
I encountered an issue when trying to add a new field in the database. I tried several things like adding a script to migrate, but didn't work, then it was not doing any changes on the DB so I tried deleting and recreating the database. But now I cannot create it again. T_T Is there any way to return the database to a clean state without recreating the entire app?

**Comment by bbelderbos** [comment]
On which branch is this so I can reproduce?
Can you record more in detail the exact steps you did and outputs you got? That will help debugging. 
Thanks.

**Comment by bbelderbos** [comment]
Also good to make a PR at that time so we can see the exact changes that led up to that. I expect a fresh new db to always work?

**Comment by bbelderbos** [comment]
@abaddonpuff please give me some more context so I can look at it tomorrow morning ...
Thanks

**Comment by abaddonpuff** [comment]
Created the pull request. Sources I found mentioned to clean the migration files. after manually removing the table through Python manage.py dbshell. So I did, and deleted just the TwitterUserPosts table. But then After executing python manage.py makemigrations -> migrate. The table was not created again.

Sorry didn't submit a PR because it was not a code change rather probably something I executed wrong but now I subimtted so you can probably see the migration files being deleted. 

Also sorry had to go to the office, had no access to my device until now.

**Comment by abaddonpuff** [comment]
Unblocked myself by pulling the repo to a different folder and re-migrating. Obviously entire DB gone and it would be amazing to understand how to fix those little problems myself.

**Comment by bbelderbos** [comment]
`dbshell` means you edited the db directly (sql level)? That should not be needed, what made you do that?

Indeed if you physically touch the db like that, you can easily run into issues (re-)running the migration files. Maybe we discard this PR so we still keep the original migration files on main, which it seems in your 2nd note you confirmed are working fine if we create a new db. 

If you have data you care about (X for example), you could still manually export them from your old db and re-import them. Let me know, but might be more effort then just call the API a few times again through the web interface ...

**Comment by abaddonpuff** [comment]
Yeah :( Internet made me do it T_T.

Yeah I think that should not be necessary. Just a good to know for now on our next review. For now I'll work on the other one that's working. Thank you so much

**Comment by bbelderbos** [comment]
ok cool, keep me posted ...
