### ISSUE TITLE
use s3 to store images

### ISSUE THREAD

**Issue by bbelderbos** [abaddonpuff/commandCenter#5]
those would not go into the postgres db, we could even use a trigger + lambda for automatic thumbnail generation

related clinic:
https://pybites.circle.so/c/circle-coaching-calls/setting-up-a-transcription-pipeline-with-aws-assembly-ai

**Comment by bbelderbos** [comment]
not sure if we need this still?

**Comment by abaddonpuff** [comment]
The images stored on X and spotify are already uploaded in the cloud. I think it doesn't make much sense to use it. Going to close

**Comment by bbelderbos** [comment]
Yeah good point, it's already in the cloud so why re-upload. We'll find another use case ...
