### ISSUE TITLE
deployment

### ISSUE THREAD

**Issue by bbelderbos** [abaddonpuff/commandCenter#53]
Let's focus on this first, overview clinic:
https://pybites.circle.so/c/pybites-coaching-calls/sections/117462/lessons/394733

I like Heroku but not free

I don't like AWS (for django) = more complex and sometimes hidden costs (see also [this discussion](https://pybites.circle.so/c/general-discussion-and-posting/deploying-a-django-app-using-aws))

Others: fly.io and render.com -> the latter has a free plan

**Comment by abaddonpuff** [comment]
I'm Checking Heroku! and experimenting a little bit. Will come with a better update by tomorrow. Still a learning curve to me.

**Comment by abaddonpuff** [comment]
Not entirely sure what I'm doing wrong. My guess is there might be some dependencies ? Need to do some digging on the errors.

`-----> Building on the Heroku-22 stack
-----> Determining which buildpack to use for this app
-----> Python app detected
-----> No Python version was specified. Using the buildpack default: python-3.12.4
       To use a different version, see: https://devcenter.heroku.com/articles/python-runtimes
-----> Installing python-3.12.4
-----> Installing pip 24.0, setuptools 69.2.0 and wheel 0.43.0
-----> Installing SQLite3
-----> Installing requirements with pip
       Collecting asgiref==3.8.1 (from -r requirements.txt (line 1))
         Downloading asgiref-3.8.1-py3-none-any.whl.metadata (9.3 kB)
       Collecting beautifulsoup4==4.12.3 (from -r requirements.txt (line 2))
         Downloading beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
       Collecting certifi==2024.2.2 (from -r requirements.txt (line 3))
         Downloading certifi-2024.2.2-py3-none-any.whl.metadata (2.2 kB)
       Collecting charset-normalizer==3.3.2 (from -r requirements.txt (line 4))
         Downloading charset_normalizer-3.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (33 kB)
       Collecting config==0.5.1 (from -r requirements.txt (line 5))
         Downloading config-0.5.1-py2.py3-none-any.whl.metadata (1.4 kB)
       Collecting Django==4.2.12 (from -r requirements.txt (line 6))
         Downloading Django-4.2.12-py3-none-any.whl.metadata (4.2 kB)
       Collecting django-bootstrap-v5==1.0.11 (from -r requirements.txt (line 7))
         Downloading django_bootstrap_v5-1.0.11-py3-none-any.whl.metadata (4.2 kB)
       Collecting idna==3.7 (from -r requirements.txt (line 8))
         Downloading idna-3.7-py3-none-any.whl.metadata (9.9 kB)
       Collecting oauthlib==3.2.2 (from -r requirements.txt (line 9))
         Downloading oauthlib-3.2.2-py3-none-any.whl.metadata (7.5 kB)
       Collecting python-dotenv==1.0.1 (from -r requirements.txt (line 10))
         Downloading python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
       Collecting requests==2.31.0 (from -r requirements.txt (line 11))
         Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
       Collecting requests-oauthlib==2.0.0 (from -r requirements.txt (line 12))
         Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl.metadata (11 kB)
       Collecting slack_bolt==1.19.0 (from -r requirements.txt (line 13))
         Downloading slack_bolt-1.19.0-py2.py3-none-any.whl.metadata (10 kB)
       Collecting slack_sdk==3.30.0 (from -r requirements.txt (line 14))
         Downloading slack_sdk-3.30.0-py2.py3-none-any.whl.metadata (15 kB)
       Collecting soupsieve==2.5 (from -r requirements.txt (line 15))
         Downloading soupsieve-2.5-py3-none-any.whl.metadata (4.7 kB)
       Collecting sqlparse==0.5.0 (from -r requirements.txt (line 16))
         Downloading sqlparse-0.5.0-py3-none-any.whl.metadata (3.9 kB)
       Collecting typing_extensions==4.12.2 (from -r requirements.txt (line 17))
         Downloading typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
       Collecting urllib3==2.2.1 (from -r requirements.txt (line 18))
         Downloading urllib3-2.2.1-py3-none-any.whl.metadata (6.4 kB)
       WARNING: The candidate selected for download or install is a yanked version: 'django' candidate (version 4.2.12 at https://files.pythonhosted.org/packages/13/b3/4462fc6d771763a273590ecd6e535f284e057f5b8cc1dd41fca774b1072c/Django-4.2.12-py3-none-any.whl (from https://pypi.org/simple/django/) (requires-python:>=3.8))
       Reason for being yanked: Release files have Windows end-of-line characters and are missing executable bits.
       Downloading asgiref-3.8.1-py3-none-any.whl (23 kB)
       Downloading beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)
       Downloading certifi-2024.2.2-py3-none-any.whl (163 kB)
       Downloading charset_normalizer-3.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (141 kB)
       Downloading config-0.5.1-py2.py3-none-any.whl (20 kB)
       Downloading Django-4.2.12-py3-none-any.whl (8.0 MB)
       Downloading django_bootstrap_v5-1.0.11-py3-none-any.whl (24 kB)
       Downloading idna-3.7-py3-none-any.whl (66 kB)
       Downloading oauthlib-3.2.2-py3-none-any.whl (151 kB)
       Downloading python_dotenv-1.0.1-py3-none-any.whl (19 kB)
       Downloading requests-2.31.0-py3-none-any.whl (62 kB)
       Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl (24 kB)
       Downloading slack_bolt-1.19.0-py2.py3-none-any.whl (198 kB)
       Downloading slack_sdk-3.30.0-py2.py3-none-any.whl (288 kB)
       Downloading soupsieve-2.5-py3-none-any.whl (36 kB)
       Downloading sqlparse-0.5.0-py3-none-any.whl (43 kB)
       Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
       Downloading urllib3-2.2.1-py3-none-any.whl (121 kB)
       Installing collected packages: config, urllib3, typing_extensions, sqlparse, soupsieve, slack_sdk, python-dotenv, oauthlib, idna, charset-normalizer, certifi, asgiref, slack_bolt, requests, Django, beautifulsoup4, requests-oauthlib, django-bootstrap-v5
       Successfully installed Django-4.2.12 asgiref-3.8.1 beautifulsoup4-4.12.3 certifi-2024.2.2 charset-normalizer-3.3.2 config-0.5.1 django-bootstrap-v5-1.0.11 idna-3.7 oauthlib-3.2.2 python-dotenv-1.0.1 requests-2.31.0 requests-oauthlib-2.0.0 slack_bolt-1.19.0 slack_sdk-3.30.0 soupsieve-2.5 sqlparse-0.5.0 typing_extensions-4.12.2 urllib3-2.2.1
-----> $ python webCommander/manage.py collectstatic --noinput
       Traceback (most recent call last):
         File "/tmp/build_13a00ee1/webCommander/manage.py", line 22, in <module>
           main()
         File "/tmp/build_13a00ee1/webCommander/manage.py", line 18, in main
           execute_from_command_line(sys.argv)
         File "/app/.heroku/python/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
           utility.execute()
         File "/app/.heroku/python/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
           self.fetch_command(subcommand).run_from_argv(self.argv)
         File "/app/.heroku/python/lib/python3.12/site-packages/django/core/management/base.py", line 412, in run_from_argv
           self.execute(*args, **cmd_options)
         File "/app/.heroku/python/lib/python3.12/site-packages/django/core/management/base.py", line 458, in execute
           output = self.handle(*args, **options)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         File "/app/.heroku/python/lib/python3.12/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 209, in handle
           collected = self.collect()
                       ^^^^^^^^^^^^^^
         File "/app/.heroku/python/lib/python3.12/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 135, in collect
           handler(path, prefixed_path, storage)
         File "/app/.heroku/python/lib/python3.12/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 368, in copy_file
           if not self.delete_file(path, prefixed_path, source_storage):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         File "/app/.heroku/python/lib/python3.12/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 278, in delete_file
           if self.storage.exists(prefixed_path):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         File "/app/.heroku/python/lib/python3.12/site-packages/django/core/files/storage/filesystem.py", line 165, in exists
           return os.path.lexists(self.path(name))
                                  ^^^^^^^^^^^^^^^
         File "/app/.heroku/python/lib/python3.12/site-packages/django/contrib/staticfiles/storage.py", line 39, in path
           raise ImproperlyConfigured(
       django.core.exceptions.ImproperlyConfigured: You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.
 !     Error while running '$ python webCommander/manage.py collectstatic --noinput'.
       See traceback above for details.
       You may need to update application code to resolve this error.
       Or, you can disable collectstatic for this application:
          $ heroku config:set DISABLE_COLLECTSTATIC=1
       https://devcenter.heroku.com/articles/django-assets
 !     Push rejected, failed to compile Python app.
 !     Push failed`

**Comment by abaddonpuff** [comment]
BTW This happens when I deploy the application to Heroku

**Comment by bbelderbos** [comment]
I got that too last week, it's when you miss this setting:

```
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
```

You also have to add `whitenoise` (that's what I use and recommend) to handle static files:

```
pip install whitenoise
```

And add its middleware in settings:

```
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
...
```

Also make sure these 2 are set:

```
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATIC_URL = '/static/'
```

And try again and let me know ...

Btw we have an old training in PDM about Heroku I forgot to link, I think it still works:
https://pybites.circle.so/c/pybites-developer-mindset-pdm-program/sections/117348/lessons/394225

**Comment by bbelderbos** [comment]
(so add whitenoise to requirements.txt actually, you also included gunicorn?)

**Comment by bbelderbos** [comment]
And this for `Procfile`? 

```
$ more Procfile
release: python manage.py migrate
web: gunicorn mysite.wsgi --log-file -
```

(replace `mysite` with the name of your Django project ...)

**Comment by abaddonpuff** [comment]
I think its there...

https://stark-escarpment-39840-ce9415be8f72.herokuapp.com

**Comment by bbelderbos** [comment]
Yep that renders, nice, but no home + login pages yet?

**Comment by bbelderbos** [comment]
glad we got this done!
