### ISSUE TITLE
SecretKey Found

### ISSUE THREAD

**Issue by abaddonpuff** [abaddonpuff/commandCenter#54]
Found  on settings

```
#SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-<redacted>'
```

Should that change? how should that be secured?

**Comment by bbelderbos** [comment]
Environment variables :)

[article] How to handle environment variables in Python
https://pybit.es/articles/how-to-handle-environment-variables-in-python/

I would go with the python-decouple package/library - just follow the steps in the article ...

You'll need at least these for Django / heroku:

```
# .env
SECRET_KEY=your-secret-key
ALLOWED_HOSTS=.localhost, .herokuapp.com
DEBUG=False
DATABASE_URL=postgres://postgres:password@0.0.0.0:5432/your-db
```

And you'll have to set the APIs/services ones as well:

<img width="788" alt="image" src="https://github.com/abaddonpuff/commandCenter/assets/387927/eb1aeead-cac3-423f-94fd-1e8ffbe11270">

Remotely -> in the Heroku gui or via its command line interface

Locally -> put them all in your (gitignored) .env file.

**Comment by bbelderbos** [comment]
done and working, you just need to set all your env variables remotely now ...
