### ISSUE TITLE
Questions to focus for Monday Code Review

### ISSUE THREAD

**Issue by abaddonpuff** [abaddonpuff/commandCenter#60]
- What is the right flow to test locally and then push to production. (I've received a bunch of errors when trying to use the local variables against the ones Heroku Uses). E.g. I would've liked for you to check some code, but I couldn't test it because I was merging to main so I could push to heroku. 
- How can I debug like I usually do locally when the app is on Heroku. (e.g database, create an admin super user for Django, execute other Django commands).
- Created a Login Page but struggled and spent a lot more time trying to learn how to debug.... made a mess with my directory but I'm still not understanding how to enforce the session to login.

**Comment by bbelderbos** [comment]
thanks, good to list these out, show me in a bit and I will guide you through it

**Comment by bbelderbos** [comment]
This guide is good for making the login page: https://learndjango.com/tutorials/django-login-and-logout-tutorial

**Comment by bbelderbos** [comment]
Is this all clear now? I think the biggest thing here was the missing env vars locally ...

**Comment by abaddonpuff** [comment]
This is all good now! Thank you!
