### ISSUE TITLE
Log in not entirely working yet / add login_required decorator

### ISSUE THREAD

**Issue by bbelderbos** [abaddonpuff/commandCenter#64]
I do have an error I cannot fix right now. When I log in everything works when authenticated. EXCEPT when I tried to read posts.... we can speak about it on Thursday, but when I try to read the posts on any of the X users, it redirects to login page as if it was not authenticated. Everything else works great.

_Originally posted by @abaddonpuff in https://github.com/abaddonpuff/commandCenter/issues/61#issuecomment-2216210022_

**Comment by bbelderbos** [comment]
Yeah let's talk about it in our next meeting, but I miss the `@login_required` decorator on your views? You need to apply this to lock down views. Can you try and update me here?

**Comment by abaddonpuff** [comment]
Login Working
